#!/bin/sh

exec 0< /dev/tty

WHITE="\e[1;37m"
GREEN="\e[1;32m"
ORANGE="\e[0;33m"
RED="\e[0;31m"
STOP="\e[0m"

#
# tf fmt
#

printf "${WHITE}"
figlet tf fmt
printf "${STOP}"

printf '%s\n' "--------"

tf_fmt=$(terraform fmt -check -recursive)

if (( ${#tf_fmt[@]} > 0 )); then
  for i in $tf_fmt; do
    terraform fmt -check -diff $i
    printf '\n'
  done
  if [ ! -z "$tf_fmt" ]; then
    printf '%s\n' "--------"
    printf '%s\n\n' "$tf_fmt"
    printf 'Commit these files..? '
    while true; do
      read -r -p "[y/n] " response
      case "$response" in
          [yY])
            terraform fmt -recursive -write=true
            for i in $tf_fmt; do
              git add $i
            done
            git commit -m 'Automated: pre-push tf formatting...'
            break
            ;;
          [nN])
            printf "${GREEN}"
            printf '"No" selected, continuing script...\n'
            printf "${STOP}"
            break
            ;;
          *)
            printf 'Please enter: '
            exit 1
          ;;
      esac
    done
  fi
else
  printf "${GREEN}"
  printf 'No formatting issues detected...\n'
  printf "${STOP}"
  printf '%s\n' "--------"
fi

#
# tflint
#

printf "${WHITE}"
figlet tf lint
printf "${STOP}"

printf '%s\n' "--------"

if [ ! $(which tflint) ]; then
  printf "${RED}"
  printf 'Error: tflint not found!\n'
  printf "${STOP}"
  exit 1
fi

for m in $(ls $(pwd)/modules/); do
  printf 'Linting module: %s\n' "$m"
  tflint --deep --module $(pwd)/modules/${m}
  
  if [ $? -eq 0 ]; then
    printf "${GREEN}"
    printf '\tNo issues found...\n'
    printf "${STOP}"
    printf '%s\n' "--------"
  else
    printf 'FAILED\n\n'
    printf '%s\n' "--------"
  fi
done



