#!/bin/sh

exec 0< /dev/tty

#
# tf fmt
#

figlet tf fmt
printf '%s\n' "--------"

tf_fmt=$(terraform fmt -check -recursive)

if [ -z "$tf_fmt" ]; then
  for i in $tf_fmt; do
    terraform fmt -check -diff $i
    printf '\n'
  done
  if [ ! -z "$tf_fmt" ]; then
    printf '%s\n' "--------"
    printf '%s\n' "$tf_fmt"
    printf 'Commit these files..? '
    while true; do
      read -r -p "[y/n] " response
      case "$response" in
          [yY])
            terraform fmt -recursive -write=true
            for i in $tf_fmt; do
              git add $i
            done
            git commit -m 'Automated: pre-push tf formatting...'
            break
            ;;
          [nN])
            printf '"No" selected, continuing script...\n'
            break
            ;;
          *)
            printf 'Please enter: '
            exit 1
          ;;
      esac
    done
  fi
else
  printf 'No formatting issues detected...\n'
  printf '%s\n' "--------"
fi

#
# tflint
#

figlet tf lint
printf '%s\n' "--------"

if [ ! $(which tflint) ]; then
  printf 'Error: tflint not found!\n'
  exit 1
fi

for m in $(ls $(pwd)/modules/); do
  printf 'Linting module: %s\n' "$m"
  tflint --deep --module $(pwd)/modules/${m}
  
  if [ $? -eq 0 ]; then
    printf '\tNo issues found...\n'
    printf '%s\n' "--------"
  else
    printf 'FAILED\n\n'
    printf '%s\n' "--------"
  fi
done



